/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker-proxy-rotation-monitor/worker-configuration.d.ts` (hash: ec95299fa681d96dfe6689c0b7581cfd)
interface __BaseEnv_Env {
	ASSETS: Fetcher;
	RATE_LIMITS: DurableObjectNamespace<import("./src/index").ProxyRateLimiter>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "ProxyRateLimiter";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
